### ISSUE TITLE
Add support to propagate byte-order for sequence

### ISSUE THREAD

**Issue by joachimmetz** [libyal/dtfabric#12]
```
name: keychain_database_schema
type: structure
attributes:
  byte_order: big-endian
members:
- name: size
  data_type: uint32
- name: number_of_tables
  data_type: uint32
- name: table_offsets
  type: sequence
  element_data_type: uint32
  number_of_elements: keychain_database_schema.number_of_tables
```

Currently byte-order does not appear to be propagated to table_offsets

* [ ] Add support to propagate byte-order for sequence
* [ ] Add tests
