### ISSUE TITLE
Add support for validation of data type values in runtime

### ISSUE THREAD

**Issue by joachimmetz** [libyal/dtfabric#17]
* signature
* known values
* integer bounds

**Comment by joachimmetz** [comment]
Idea add validation as validation rules:

```
name: tzif_file_header
type: structure
description: file header.
attributes:
  byte_order: big-endian
validation:
  - tzif_file_header.signature == "TZif"
members:
- name: signature
  type: stream
  element_data_type: byte
  number_of_elements: 4
- name: format_version
  data_type: byte
```
